import type { ComponentType } from "react";
import {
  Activity,
  Atom,
  Award,
  BadgeCheck,
  BarChart3,
  Beaker,
  Bolt,
  Box,
  Boxes,
  Building2,
  Cable,
  CircuitBoard,
  ClipboardCheck,
  Cog,
  Combine,
  Compass,
  Component,
  Container,
  Cpu,
  Droplet,
  Factory,
  FileCheck2,
  FileText,
  Filter,
  Flame,
  FlameKindling,
  FlaskConical,
  Fuel,
  Gauge,
  Globe2,
  Handshake,
  Headset,
  Layers,
  Layers3,
  Leaf,
  Lightbulb,
  LineChart,
  ListChecks,
  Magnet,
  MapPin,
  Microscope,
  Network,
  Orbit,
  Package,
  Plane,
  Recycle,
  Route,
  Ruler,
  ScanLine,
  Scissors,
  Settings,
  Shapes,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Spool,
  Sun,
  Target,
  Thermometer,
  TrendingUp,
  Trees,
  Truck,
  Users,
  Waves,
  Wind,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Content files are plain data so they stay serialisable and easy to review.
 * They name an icon with a string, and this registry is the only place that
 * maps those names onto components.
 */
export const iconRegistry = {
  activity: Activity,
  atom: Atom,
  award: Award,
  badge: BadgeCheck,
  bars: BarChart3,
  beaker: Beaker,
  bolt: Bolt,
  box: Box,
  boxes: Boxes,
  building: Building2,
  cable: Cable,
  circuit: CircuitBoard,
  clipboard: ClipboardCheck,
  cog: Cog,
  combine: Combine,
  compass: Compass,
  component: Component,
  container: Container,
  cpu: Cpu,
  droplet: Droplet,
  factory: Factory,
  file: FileText,
  fileCheck: FileCheck2,
  filter: Filter,
  flame: Flame,
  flameKindling: FlameKindling,
  flask: FlaskConical,
  fuel: Fuel,
  gauge: Gauge,
  globe: Globe2,
  handshake: Handshake,
  headset: Headset,
  layers: Layers,
  layers3: Layers3,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lineChart: LineChart,
  listChecks: ListChecks,
  magnet: Magnet,
  mapPin: MapPin,
  microscope: Microscope,
  network: Network,
  orbit: Orbit,
  package: Package,
  plane: Plane,
  recycle: Recycle,
  route: Route,
  ruler: Ruler,
  scan: ScanLine,
  scissors: Scissors,
  settings: Settings,
  shapes: Shapes,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  spark: Sparkles,
  spool: Spool,
  sun: Sun,
  target: Target,
  thermometer: Thermometer,
  trending: TrendingUp,
  trees: Trees,
  truck: Truck,
  users: Users,
  waves: Waves,
  wind: Wind,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, ComponentType<{ className?: string; size?: number }>>;

export type IconName = keyof typeof iconRegistry;

export function getIcon(name: IconName) {
  return iconRegistry[name];
}
